## BERT embedding POC

In [1]:
import mxnet as mx
from bert_embedding import BertEmbedding

bert_abstract = """We introduce a new language representation model called BERT, which stands for Bidirectional Encoder Representations from Transformers.
 Unlike recent language representation models, BERT is designed to pre-train deep bidirectional representations by jointly conditioning on both left and right context in all layers.
 As a result, the pre-trained BERT representations can be fine-tuned with just one additional output layer to create state-of-the-art models for a wide range of tasks, such as question answering and language inference, without substantial task-specific architecture modifications. 
BERT is conceptually simple and empirically powerful.
We a new test.
It obtains new state-of-the-art results on eleven natural language processing tasks, including pushing the GLUE benchmark to 80.4% (7.6% absolute improvement), MultiNLI accuracy to 86.7 (5.6% absolute improvement) and the SQuAD v1.1 question answering Test F1 to 93.2 (1.5% absolute improvement), outperforming human performance by 2.0%."""
sentences = bert_abstract.split('\n')
#ctx = mx.gpu(0)
bert_embedding = BertEmbedding()

In [2]:
sentences

['We introduce a new language representation model called BERT, which stands for Bidirectional Encoder Representations from Transformers.',
 ' Unlike recent language representation models, BERT is designed to pre-train deep bidirectional representations by jointly conditioning on both left and right context in all layers.',
 ' As a result, the pre-trained BERT representations can be fine-tuned with just one additional output layer to create state-of-the-art models for a wide range of tasks, such as question answering and language inference, without substantial task-specific architecture modifications. ',
 'BERT is conceptually simple and empirically powerful.',
 'We a new test.',
 'It obtains new state-of-the-art results on eleven natural language processing tasks, including pushing the GLUE benchmark to 80.4% (7.6% absolute improvement), MultiNLI accuracy to 86.7 (5.6% absolute improvement) and the SQuAD v1.1 question answering Test F1 to 93.2 (1.5% absolute improvement), outperformin

In [3]:
result = bert_embedding(sentences, 'avg')

In [4]:
result[0][0][0], result[0][1][0]

('we',
 array([ 4.79647905e-01,  1.82488203e-01, -2.85975277e-01, -4.65674043e-01,
         1.24902315e-02, -7.43049532e-02, -1.80172503e-01,  3.78131807e-01,
         9.13512528e-01, -2.52958179e-01, -4.32432830e-01,  1.20841816e-01,
        -4.39302057e-01, -1.42209038e-01,  1.45702541e-01, -1.12910770e-01,
         3.57749671e-01,  1.14916228e-01,  1.28566056e-01,  3.41200233e-01,
         3.63360047e-02,  2.77825505e-01, -4.53675866e-01,  8.64902258e-01,
         2.76046455e-01, -4.23001051e-01, -5.79821691e-03, -3.06109965e-01,
        -5.90147257e-01, -2.27048278e-01,  1.02910772e-01,  5.07021435e-02,
        -1.50824171e-02, -3.90145153e-01, -3.19009721e-01,  4.43181634e-01,
         2.70800978e-01,  5.69034040e-01, -1.09156519e-01, -2.25051120e-03,
        -1.40458643e-01, -4.54779789e-02,  1.93256900e-01,  2.68915296e-01,
        -2.12611437e-01, -7.56629765e-01,  1.19546041e-01, -4.67385620e-01,
        -7.24064350e-01, -1.32616270e+00, -7.24923730e-01, -1.07705072e-02,
     

In [5]:
result[4][0][0], result[4][1][0]

('we',
 array([ 2.44056851e-01, -1.88854448e-02,  7.46956348e-01, -5.12621030e-02,
         1.23291276e-01,  1.22659625e-02,  3.27967495e-01,  3.25916469e-01,
         8.19641531e-01, -6.94205880e-01,  3.77520859e-01,  5.07798612e-01,
         1.80669859e-01,  7.27102101e-01, -2.91524172e-01,  1.27198994e-01,
         3.87319863e-01,  2.29832008e-02,  5.56116462e-01, -4.52264607e-01,
         5.14224231e-01, -7.72015303e-02,  5.09402812e-01, -4.48732413e-02,
        -3.10238391e-01,  2.59754539e-01, -1.05229788e-01, -5.21747112e-01,
        -2.24417090e-01, -2.34627217e-01, -6.28089786e-01, -2.99867857e-02,
        -1.47526503e-01, -5.95587313e-01, -7.33270526e-01,  2.62820721e-01,
         2.37073656e-02,  2.74176478e-01, -5.00684500e-01,  3.47243845e-02,
         2.47265518e-01, -1.16760480e+00, -1.17742717e-01,  1.30031556e-02,
        -4.82070416e-01, -3.85395586e-01, -7.53150761e-01, -6.63940702e-03,
        -2.14567602e-01, -3.11435848e-01, -4.35626060e-01, -2.30504096e-01,
     

In [6]:
len(result), len(result[0][0]), len(result[0][1]), len(result[0][1][2])

(6, 18, 18, 768)

### Keras bert

In [11]:
import keras
from keras_bert import get_base_dict, get_model, compile_model, gen_batch_inputs


# A toy input example
sentence_pairs = [
    [['all', 'work', 'and', 'no', 'play'], ['makes', 'jack', 'a', 'dull', 'boy']],
    [['from', 'the', 'day', 'forth'], ['my', 'arm', 'changed']],
    [['and', 'a', 'voice', 'echoed'], ['power', 'give', 'me', 'more', 'power']],
]


# Build token dictionary
token_dict = get_base_dict()  # A dict that contains some special tokens
for pairs in sentence_pairs:
    for token in pairs[0] + pairs[1]:
        if token not in token_dict:
            token_dict[token] = len(token_dict)
token_list = list(token_dict.keys())  # Used for selecting a random word


# Build & train the model
model = get_model(
    token_num=len(token_dict),
    head_num=5,
    transformer_num=12,
    embed_dim=25,
    feed_forward_dim=100,
    seq_len=20,
    pos_num=20,
    dropout_rate=0.05,
)
compile_model(model)
model.summary()

def _generator():
    while True:
        yield gen_batch_inputs(
            sentence_pairs,
            token_dict,
            token_list,
            seq_len=20,
            mask_rate=0.3,
            swap_sentence_rate=1.0,
        )

model.fit_generator(
    generator=_generator(),
    steps_per_epoch=1000,
    epochs=1,
    validation_data=_generator(),
    validation_steps=100,
    callbacks=[
        keras.callbacks.EarlyStopping(monitor='val_loss', patience=5)
    ],
)


# Use the trained model
inputs, output_layer = get_model(
    token_num=len(token_dict),
    head_num=5,
    transformer_num=12,
    embed_dim=300,
    feed_forward_dim=100,
    seq_len=20,
    pos_num=20,
    dropout_rate=0.05,
    training=False,      # The input layers and output layer will be returned if `training` is `False`
    trainable=False,     # Whether the model is trainable. The default value is the same with `training`
    output_layer_num=4,  # The number of layers whose outputs will be concatenated as a single output.
                         # Only available when `training` is `False`.
)

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
Input-Token (InputLayer)        (None, 20)           0                                            
__________________________________________________________________________________________________
Input-Segment (InputLayer)      (None, 20)           0                                            
__________________________________________________________________________________________________
Embedding-Token (TokenEmbedding [(None, 20, 25), (28 700         Input-Token[0][0]                
__________________________________________________________________________________________________
Embedding-Segment (Embedding)   (None, 20, 25)       50          Input-Segment[0][0]              
__________________________________________________________________________________________________
Embedding-

Epoch 1/1
1000/1000 [==============================] - 54s 54ms/step - loss: 3.9721 - MLM_loss: 3.3211 - NSP_loss: 0.6510 - val_loss: 3.8928 - val_MLM_loss: 3.3064 - val_NSP_loss: 0.5864


In [6]:
sentence_pairs

[[['all', 'work', 'and', 'no', 'play'], ['makes', 'jack', 'a', 'dull', 'boy']],
 [['from', 'the', 'day', 'forth'], ['my', 'arm', 'changed']],
 [['and', 'a', 'voice', 'echoed'], ['power', 'give', 'me', 'more', 'power']]]

In [7]:
token_dict

{'': 0,
 '[CLS]': 2,
 '[MASK]': 4,
 '[SEP]': 3,
 '[UNK]': 1,
 'a': 12,
 'all': 5,
 'and': 7,
 'arm': 20,
 'boy': 14,
 'changed': 21,
 'day': 17,
 'dull': 13,
 'echoed': 23,
 'forth': 18,
 'from': 15,
 'give': 25,
 'jack': 11,
 'makes': 10,
 'me': 26,
 'more': 27,
 'my': 19,
 'no': 8,
 'play': 9,
 'power': 24,
 'the': 16,
 'voice': 22,
 'work': 6}

In [8]:
token_list

['',
 'arm',
 'play',
 'all',
 'forth',
 'voice',
 'and',
 'from',
 'power',
 'my',
 '[MASK]',
 'echoed',
 'the',
 'no',
 '[SEP]',
 'give',
 'a',
 '[UNK]',
 'changed',
 'day',
 'dull',
 'me',
 'more',
 'boy',
 '[CLS]',
 'jack',
 'makes',
 'work']

In [12]:
gen_batch_inputs(
            sentence_pairs,
            token_dict,
            token_list,
            seq_len=20,
            mask_rate=0.3,
            swap_sentence_rate=1.0,
        )

([array([[ 2,  5,  6,  4,  4,  9,  3, 19,  4, 21,  3,  0,  0,  0,  0,  0,
           0,  0,  0,  0],
         [ 2,  4, 16,  4, 18,  3,  4, 25, 26, 27, 24,  3,  0,  0,  0,  0,
           0,  0,  0,  0],
         [ 2,  7,  4, 22, 23,  3,  4, 11, 12, 13, 14,  3,  0,  0,  0,  0,
           0,  0,  0,  0]]),
  array([[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]),
  array([[0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])],
 [array([[[ 2],
          [ 5],
          [ 6],
          [ 7],
          [ 8],
          [ 9],
          [ 3],
          [19],
          [20],
          [21],
          [ 3],
          [ 0],
          [ 0],
          [ 0],
          [ 0],
          [ 0],
        

In [1]:
import os
import keras

from __future__ import print_function, division

from keras.layers import Conv1D, Input, Add, Activation, Dropout, Embedding, MaxPooling1D, \
    GlobalMaxPool1D, Flatten, Dense, Concatenate, BatchNormalization
from keras.models import Sequential, Model
from keras.regularizers import l2
from keras.initializers import TruncatedNormal
from keras import optimizers

pretrained_path = 'uncased_L-12_H-768_A-12'
config_path = os.path.join(pretrained_path, 'bert_config.json')
model_path = os.path.join(pretrained_path, 'bert_model.ckpt')

Using TensorFlow backend.


In [2]:
import os
from tqdm import tqdm_notebook as tqdm
import matplotlib.pyplot as plt
import sys
from annoy import AnnoyIndex
nb_dir = os.path.split(os.getcwd())[0]
if nb_dir not in sys.path:
    sys.path.append(nb_dir)

In [3]:
MAX_SEQUENCE_LENGTH_T = 20 # 40
MAX_SEQUENCE_LENGTH_D = 512 # 200
EMBEDDING_DIM = 300
MAX_NB_WORDS = 20000

In [4]:
# Domain to use
DOMAIN = 'eclipse'
METHOD = 'propose_bert'
# Dataset paths
DIR = 'data/processed/{}'.format(DOMAIN)
DIR_PAIRS = 'data/normalized/{}'.format(DOMAIN)
DATASET = os.path.join('data/normalized/{}'.format(DOMAIN), '{}.csv'.format(DOMAIN))
# Path embeddings
EMBED_DIR='data/embed'
# Save model
SAVE_PATH = '{}_feature@number_of_epochs@epochs_64batch({})'.format(METHOD, DOMAIN)
SAVE_PATH_FEATURE = '{}_feature_@number_of_epochs@epochs_64batch({})'.format(METHOD, DOMAIN)

# Extract CORPUs
EXTRACT_CORPUS = False

In [5]:
from methods.baseline import Baseline
from methods.experiments import Experiment
from methods.evaluation import Evaluation
from methods.retrieval import Retrieval

In [6]:
baseline = Baseline(DIR, DATASET, MAX_SEQUENCE_LENGTH_T, MAX_SEQUENCE_LENGTH_D)
evaluation = Evaluation(verbose=0)
retrieval = Retrieval()
experiment = Experiment(baseline, evaluation)

In [7]:
from keras_bert import load_trained_model_from_checkpoint
from keras_bert import compile_model

def bert_model(MAX_SEQUENCE_LENGTH_D):
#     model = load_trained_model_from_checkpoint(
#             config_path,
#             model_path,
#             training=True,
#             trainable=True,
#             seq_len=MAX_SEQUENCE_LENGTH_D,
#         )
    
    layer_num = 12
    #with tf.get_default_graph().as_default():
    model = load_trained_model_from_checkpoint(
        config_path,
        model_path,
        training=False,
        use_adapter=True,
        trainable=['Encoder-{}-MultiHeadSelfAttention-Adapter'.format(i + 1) for i in range(layer_num)] +
        ['Encoder-{}-FeedForward-Adapter'.format(i + 1) for i in range(layer_num)] +
        ['Encoder-{}-MultiHeadSelfAttention-Norm'.format(i + 1) for i in range(layer_num)] +
        ['Encoder-{}-FeedForward-Norm'.format(i + 1) for i in range(layer_num)],
    )
    compile_model(model)
#     inputs = model.inputs[:2]
#     outputs = model.get_layer('Encoder-12-FeedForward-Norm').output
    
#     model = keras.models.Model(inputs, outputs, 'FeatureBERTGenerationModel')
    
    return model

In [8]:
keras.backend.clear_session()
desc_feature_model = bert_model(512)
desc_feature_model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
Input-Token (InputLayer)        (None, 512)          0                                            
__________________________________________________________________________________________________
Input-Segment (InputLayer)      (None, 512)          0                                            
__________________________________________________________________________________________________
Embedding-Token (TokenEmbedding [(None, 512, 768), ( 23440896    Input-Token[0][0]                
__________________________________________________________________________________________________
Embedding-Segment (Embedding)   (None, 512, 768)     1536        Input-Segment[0][0]              
__________________________________________________________________________________________________
Embedding-

In [9]:
from keras.models import Sequential, Model

inputs = desc_feature_model.inputs
outputs = desc_feature_model.get_layer('Encoder-12-FeedForward-Norm').output
model = Model(inputs, outputs, name='FeatureBERTGenerationModel')

In [10]:
model.name

'FeatureBERTGenerationModel'